/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolibrerias;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melina
 */
public class ModificarLibro extends javax.swing.JFrame {
        ListaSimple listaLibs = ListaSimple.getLibrariesInstance();
        JPanel panel = new JPanel();
    /**
     * Creates new form ModificarLibro
     */
    public ModificarLibro() {
        initComponents();
        setSize(833,564);
        setLibraries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblEscoja = new javax.swing.JLabel();
        lblEscoja2 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblIndice = new javax.swing.JLabel();
        spIssn = new javax.swing.JSpinner();
        btnAceptar = new javax.swing.JButton();
        cbLibreria = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Libreria", "Issn", "Nombre", "Precio", "Tema", "Disponibles", "Vendidas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLibros);
        if (tblLibros.getColumnModel().getColumnCount() > 0) {
            tblLibros.getColumnModel().getColumn(0).setResizable(false);
            tblLibros.getColumnModel().getColumn(1).setResizable(false);
            tblLibros.getColumnModel().getColumn(2).setResizable(false);
            tblLibros.getColumnModel().getColumn(3).setResizable(false);
            tblLibros.getColumnModel().getColumn(4).setResizable(false);
            tblLibros.getColumnModel().getColumn(5).setResizable(false);
            tblLibros.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 190, 720, 150);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lblTitulo.setText("Libros disponibles");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(270, 30, 281, 48);

        lblEscoja.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblEscoja.setText("Librería donde se encuentra");
        getContentPane().add(lblEscoja);
        lblEscoja.setBounds(110, 90, 250, 27);

        lblEscoja2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblEscoja2.setText("el libro a modificar:");
        getContentPane().add(lblEscoja2);
        lblEscoja2.setBounds(160, 120, 170, 27);

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("");
        btnModificar.setName("btnBuscar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(220, 440, 137, 56);

        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setName("btnBuscar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(480, 440, 137, 56);

        lblIndice.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblIndice.setForeground(new java.awt.Color(255, 255, 255));
        lblIndice.setText("Issn del libro:");
        getContentPane().add(lblIndice);
        lblIndice.setBounds(300, 370, 108, 27);
        getContentPane().add(spIssn);
        spIssn.setBounds(440, 370, 70, 30);

        btnAceptar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        btnAceptar.setName("btnBuscar"); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(590, 100, 100, 50);

        cbLibreria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLibreriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbLibreria);
        cbLibreria.setBounds(370, 110, 160, 27);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-20, -10, 880, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setTable(String pNombre){
        DefaultTableModel model = new DefaultTableModel();
        tblLibros.setModel(model);
        model.addColumn("Libreria");
        model.addColumn("Issn");
        model.addColumn("Nombre");
        model.addColumn("Precio");
        model.addColumn("Tema");
        model.addColumn("Disponibles");
        model.addColumn("Vendidos");
        tblLibros.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblLibros.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblLibros.getColumnModel().getColumn(3).setPreferredWidth(40);
        tblLibros.getColumnModel().getColumn(6).setPreferredWidth(30);
        tblLibros.getColumnModel().getColumn(5).setPreferredWidth(40);
        for (int index = 0; index < listaLibs.getSize(); index++){
            Libreria libreria = (Libreria)listaLibs.goToPos(index);
            if (pNombre.equals(libreria.getNombre())){
                for (int cont = 0; cont < libreria.getListaLibros().getSize(); cont++){
                    Libro libro = (Libro)libreria.getListaLibros().goToPos(cont);
                    model.addRow(new Object[]{libreria.getNombre(),libro.getIssn(),libro.getNombre(),libro.getPrecio(),libro.getTema(),libro.getCantDisponible(),libro.getCantVendida()});
                }
                break;
            }
        }
    }
    private void setLibraries(){
        cbLibreria.removeAllItems();
        if (listaLibs.getSize() == 0){
            JOptionPane.showMessageDialog(panel, "Actualmente no hay librerías disponibles.", "Error", JOptionPane.ERROR_MESSAGE);
            hide();
        }
        else{
            int indice = 0;
            while (indice < listaLibs.getSize()){
                Libreria temporal = (Libreria)listaLibs.goToPos(indice);
                cbLibreria.addItem(temporal.getNombre());
                indice++;
            }
        }
        
    }
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Libro book = (Libro)listaLibs.buscarPersonalizado(cbLibreria.getSelectedItem().toString(), Integer.parseInt(spIssn.getValue().toString()));
        new DatosLibro(book).setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean validar = (boolean)listaLibs.eliminarPersonalizado(cbLibreria.getSelectedItem().toString(), Integer.parseInt(spIssn.getValue().toString()));
        if (validar){
            JOptionPane.showMessageDialog(panel, "El libro se ha eliminado correctamente.", "Libro eliminado", JOptionPane.INFORMATION_MESSAGE);
            setTable(cbLibreria.getSelectedItem().toString());
        }
        else{
            JOptionPane.showMessageDialog(panel, "Issn no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLibreriaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        setTable(cbLibreria.getSelectedItem().toString());
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbLibreria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEscoja;
    private javax.swing.JLabel lblEscoja2;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spIssn;
    private javax.swing.JTable tblLibros;
    // End of variables declaration//GEN-END:variables
}
