/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolibrerias;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melina
 */
public class ModificarLibro extends javax.swing.JFrame {

    /**
     * Creates new form ModificarLibro
     */
    public ModificarLibro() {
        initComponents();
        setLibraries();
        setSize(648,564);
        DefaultTableModel model = new DefaultTableModel();
        tblLibros.setModel(model);
        model.addColumn("Indice");
        model.addColumn("Nombre");
        model.addColumn("Disponibles");
        model.addColumn("Vendidos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblEscoja = new javax.swing.JLabel();
        lblEscoja2 = new javax.swing.JLabel();
        cbLibreria = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblIndice = new javax.swing.JLabel();
        spIndice = new javax.swing.JSpinner();
        lblBackground = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(44, 207, 549, 135);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lblTitulo.setText("Libros disponibles");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(190, 30, 281, 48);

        lblEscoja.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblEscoja.setText("Escoja la librería donde se encuentra");
        getContentPane().add(lblEscoja);
        lblEscoja.setBounds(50, 110, 305, 27);

        lblEscoja2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblEscoja2.setText("el libro que desea modificar");
        getContentPane().add(lblEscoja2);
        lblEscoja2.setBounds(80, 140, 231, 27);

        cbLibreria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLibreria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLibreriaItemStateChanged(evt);
            }
        });
        cbLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLibreriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbLibreria);
        cbLibreria.setBounds(390, 120, 160, 27);

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("");
        btnModificar.setName("btnBuscar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(160, 420, 137, 56);

        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setName("btnBuscar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(330, 420, 137, 56);

        lblIndice.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblIndice.setForeground(new java.awt.Color(255, 255, 255));
        lblIndice.setText("Indice del libro:");
        getContentPane().add(lblIndice);
        lblIndice.setBounds(170, 370, 126, 27);
        getContentPane().add(spIndice);
        spIndice.setBounds(330, 370, 70, 22);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-10, -10, 710, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setLibraries(){
        cbLibreria.removeAllItems();
        JPanel panel = new JPanel();
        ListaSimple listaLibs = ListaSimple.getLibrariesInstance();
        if (listaLibs.getSize() == 0){
            JOptionPane.showMessageDialog(panel, "Actualmente no hay librerías disponibles.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int indice = 0;
            while (indice < listaLibs.getSize()){
                Libreria temporal = (Libreria)listaLibs.goToPos(indice);
                cbLibreria.addItem(temporal.getNombre());
                indice++;
            }
        }
    }
    private void cbLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLibreriaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbLibreriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLibreriaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLibreriaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbLibreria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEscoja;
    private javax.swing.JLabel lblEscoja2;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spIndice;
    private javax.swing.JTable tblLibros;
    // End of variables declaration//GEN-END:variables
}
