/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolibrerias;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Melina
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setSize(778,586);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistro = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblCédula = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        lblRegistro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lblRegistro.setText("Registro");
        getContentPane().add(lblRegistro);
        lblRegistro.setBounds(320, 20, 128, 48);

        lblNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(130, 160, 75, 27);

        txtCedula.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula);
        txtCedula.setBounds(220, 100, 360, 29);

        lblCédula.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblCédula.setText("Cédula:");
        getContentPane().add(lblCédula);
        lblCédula.setBounds(140, 100, 62, 27);

        txtNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(220, 160, 360, 29);

        lblCorreo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblCorreo.setText("Correo electrónico:");
        getContentPane().add(lblCorreo);
        lblCorreo.setBounds(50, 400, 159, 27);

        txtTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(220, 350, 360, 29);

        txtCorreo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(220, 400, 360, 29);

        lblDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblDireccion.setText("Dirección:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(120, 220, 83, 27);

        lblTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        lblTelefono.setText("Teléfono:");
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(120, 350, 77, 27);

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 220, 360, 106);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(320, 460, 107, 59);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-20, 0, 900, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean verificar(String pCedula, ListaSimple listaClientes){
        String verificador;
        //Se busca que ya no haya otra libreria registrada con ese nombre
        for (int pos = 0; pos < listaClientes.getSize(); pos++){
            Cliente temporal = (Cliente)listaClientes.goToPos(pos);
            if (temporal == null){
                return false;
            }
            else{
                verificador = temporal.getCedula();
                if (verificador.equals(pCedula)){
                    return false;
                }
            }
        }
        return true;
    }
    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        if (txtNombre.getText().isEmpty() | txtCedula.getText().isEmpty()){
            JOptionPane.showMessageDialog(panel, "Por favor, no deje espacios en blanco.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDireccion.getText().isEmpty() | txtCorreo.getText().isEmpty()){
            JOptionPane.showMessageDialog(panel, "Por favor, no deje espacios en blanco.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Cliente nuevoCliente = new Cliente(txtCedula.getText(),txtNombre.getText(),txtDireccion.getText(),txtTelefono.getText(),txtCorreo.getText());
            ListaSimple listaClientes = ListaSimple.getClientsInstance();
            boolean verificacion = verificar(nuevoCliente.cedula,listaClientes);
            if (verificacion){
                listaClientes.append(nuevoCliente);
                JOptionPane.showMessageDialog(panel, "Usted se ha registrado correctamente", "Registro completado", JOptionPane.INFORMATION_MESSAGE);
                txtNombre.setText("");
                txtCedula.setText("");
                txtDireccion.setText("");
                txtCorreo.setText("");
                txtTelefono.setText("");
            }
            else{
                JOptionPane.showMessageDialog(panel, "Ya existe un cliente con este número de cúdula.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCédula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
